In [2]:
import numpy as np

In [3]:
vector_of_zeros = np.zeros(10)

In [5]:
memory_size = vector_of_zeros.size * vector_of_zeros.itemsize
print(memory_size)

80


In [ ]:
# pydoc numpy.add

In [10]:
vec = np.arange(10, 50)
print(vec)
print(vec[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
ran = np.arange(9)
mat = np.reshape(ran, (3, 3))
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
arr = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(arr)
print(nonzero_indices)

(array([0, 1, 4]),)


In [13]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
row_values = np.arange(5)
matrix = np.tile(row_values, (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [15]:
vector = np.linspace(0 + 1e-10, 1 - 1e-10, 10)
print(vector)

[1.00000000e-10 1.11111111e-01 2.22222222e-01 3.33333333e-01
 4.44444444e-01 5.55555556e-01 6.66666667e-01 7.77777778e-01
 8.88888889e-01 1.00000000e+00]


In [16]:
random_vector = np.random.rand(10)
sorted_vector = np.sort(random_vector)

print("Random Vector:")
print(random_vector)

print("\nSorted Vector:")
print(sorted_vector)

Random Vector:
[0.62742379 0.17283385 0.5530763  0.05607955 0.75759765 0.69421049
 0.82356505 0.45689828 0.08079454 0.58877972]

Sorted Vector:
[0.05607955 0.08079454 0.17283385 0.45689828 0.5530763  0.58877972
 0.62742379 0.69421049 0.75759765 0.82356505]


In [17]:
print("Integer types:")
print("int8:", np.iinfo(np.int8).min, np.iinfo(np.int8).max)
print("int32:", np.iinfo(np.int32).min, np.iinfo(np.int32).max)
print("int64:", np.iinfo(np.int64).min, np.iinfo(np.int64).max)

print("\nFloating-point types:")
print("float32:", np.finfo(np.float32).min, np.finfo(np.float32).max)
print("float64:", np.finfo(np.float64).min, np.finfo(np.float64).max)

Integer types:
int8: -128 127
int32: -2147483648 2147483647
int64: -9223372036854775808 9223372036854775807

Floating-point types:
float32: -3.4028235e+38 3.4028235e+38
float64: -1.7976931348623157e+308 1.7976931348623157e+308


In [18]:
float_array = np.array([1.5, 2.7, 3.8, 4.2], dtype=np.float32)
float_array = float_array.astype(np.int32)

print("Float array (converted to int32):", float_array)

Float array (converted to int32): [1 2 3 4]


In [19]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_means = np.mean(matrix, axis=1)
matrix_subtracted = matrix - row_means[:, np.newaxis]

print("Original matrix:")
print(matrix)

print("\nRow means:")
print(row_means)

print("\nMatrix with mean subtracted from each row:")
print(matrix_subtracted)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row means:
[2. 5. 8.]

Matrix with mean subtracted from each row:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [20]:
array = np.array([[3, 6, 1],
                  [9, 2, 8],
                  [5, 4, 7]])

nth_column = 1
sorted_indices = np.argsort(array[:, nth_column])
sorted_array = array[sorted_indices]

print("Original array:")
print(array)

print("\nArray sorted by the nth column:")
print(sorted_array)

Original array:
[[3 6 1]
 [9 2 8]
 [5 4 7]]

Array sorted by the nth column:
[[9 2 8]
 [5 4 7]
 [3 6 1]]


In [22]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

array[0], array[2] = array[2], array[0]

print("Original array:")
print(array)

Original array:
[[7 8 9]
 [4 5 6]
 [7 8 9]]
